name: 'publish'
on: [push, pull_request]


jobs:
  upload-artifact:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: build release
        run: cargo build --release
      - name: rename windows config and move exutable
        if: matrix.platform == 'windows-latest'
        run: copy ./target/release/ship-monitor-astro-rocket.exe .
      - name: rename linux and mac config and move exutable
        if: matrix.platform != 'windows-latest'
        run: cp ./target/release/ship-monitor-astro-rocket .


      - name: upload windows-artefact
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'windows-latest'
        with:
          name: windows-artifact
          path: |
            ship-monitor-astro-rocket.exe
            src/


      - name: upload linux-artifact
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: linux-artifact
          path: |
            ship-monitor-astro-rocket
            src/


      - name: upload macos-artifact
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'macos-latest'
        with:
          name: mac-artifact
          path: |
            ship-monitor-astro-rocket
            src/